version: '3'
services:
  app:
    build: .
    ports:
     - "5000:5000"
    depends_on:
     - postgres
    restart: on-failure
    environment:
     - POSTGRES_HOST=postgres
  postgres:
    image: postgres:12.1
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=user
     - POSTGRES_PASSWORD=testing-password
     - POSTGRES_DB=production


